/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.2020.project.drinkfactorymachinesatemachine;

import fr.univcotedazur.polytech.si4.fsm.2020.project.IStatemachine;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDrinkFactoryMachineSateMachineStatemachine extends IStatemachine {
	public interface SCInterface {
	
		public void raiseCof_Btn();
		
		public void raiseExp_Btn();
		
		public void raiseTea_Btn();
		
		public void raiseSoup_Btn();
		
		public void raiseIceTea_Btn();
		
		public void raiseCoins50_Btn();
		
		public void raiseCoins25_Btn();
		
		public void raiseCoins10_Btn();
		
		public void raiseNFC_Btn();
		
		public void raiseCancle_Btn();
		
		public void raiseAddCup_Btn();
		
		public void raiseSuger_Slider();
		
		public void raiseSize_Slider();
		
		public void raiseTem_Slider();
		
		public boolean isRaisedDoReset();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoResetRaised();
		}
	
	public SCInterface getSCInterface();
	
}
